# 디버그 로그레벨 설정하는 방법
# 기본레벨은 info 이고 너무많이 남기면 볼 수 없기 때문에.
# TRACE : 다나옴
# DEBUG : 조금 덜 나옴
# INFO : 덜나옴
# WARN : 조금나옴
# ERROR : 에러만나옴
logging:
  level:
    root: info

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://localhost:3306/likelion-db
    username: root
    password: password